# Generated by Django 2.0.3 on 2018-04-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_dtae',
            new_name='pub_date',
        ),
    ]
